name: CI/CD Workflow for AppMovilBarbada

on:
  push:
    branches:
      - master
      - Errors
      - Feature
  pull_request:
    types: [opened, closed]
    branches:
      - master

  workflow_dispatch:  # Permite ejecutar el flujo manualmente

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']  # Asegúrate de usar la versión de Node.js compatible con tu proyecto.

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cache para dependencias npm
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-node-${{ matrix.node-version }}

      # 3. Configuración de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 4. Instalación de Expo CLI
      - name: Install Expo CLI
        run: npm install --global expo-cli

      # 5. Instalación de dependencias
      - name: Install dependencies
        run: npm install

      # 6. Linter del código
      - name: Lint code with Expo
        run: expo lint --max-warnings=0

      # 7. Pruebas unitarias
      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/master'  # Solo ejecuta este job en la rama master
    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalación de EAS CLI (Expo Application Services)
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # 3. Instalación de dependencias
      - name: Install dependencies
        run: npm install

      # 4. Construcción para Android
      - name: Build APK for Android
        run: npx eas-cli build --platform android --profile preview
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  # Asegúrate de configurar EXPO_TOKEN en GitHub Secrets.

      # 5. Construcción para iOS (opcional, si es necesario)
      - name: Build for iOS
        if: github.event_name == 'workflow_dispatch'  # Solo ejecuta esto manualmente
        run: npx eas-cli build --platform ios --profile preview
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # Notificación de fallo a Slack
      - name: Send Slack notification on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"🚨 CI/CD falló en la rama ${{ github.ref_name }}. Revisa los detalles aquí: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # Notificación de éxito a Slack
      - name: Send Slack notification on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ CI/CD completado exitosamente en la rama ${{ github.ref_name }}. Revisa los detalles aquí: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  notify_pr_comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      # Agregar comentarios al Pull Request
      - name: Add comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github');
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🚀 Pull Request actualizado. Por favor revisa los últimos cambios."
            })
